### ISSUE TITLE
🐛  Chromatic Hotfix

### ISSUE THREAD

**Issue by choi2601** [DreamIn-Developer/client#12]
## 설명
- Chromatic Token Error 해결

## todos
 - [x] 발급 받은 Token 바로 대입
 - [x] yml 파일 형식 지켜서 Token 대입
 - [x] storybook main.js config 수정
 - [x] github workflows token 추가
