### ISSUE TITLE
✨ Work View Page

### ISSUE THREAD

**Issue by te-ing** [DreamIn-Developer/client#64]
## todos
 - [ ] 작품보기 페이지 레이아웃 구현
 - [ ] 좋아요, 스크랩, 팔로우 기능 구현
 - [ ] 유저 정보 클릭 시 route 기능 구현
